Rewrite functional tests with ragger.
LedgerHQ/app-xrp pull request #30
Opened 2023-03-02 14:48 UTC by agrojean-ledger

2023-03-02 16:31 UTC, agrojean-ledger commented on tests/requirements.txt
> +# pytest>=6.1.1,<7.0.0
I'll clean this up before merge. Forgot to remove commented obsolete requirements.

2023-03-02 18:07 UTC, tdejoigny-ledger requested changes

2023-03-02 18:07 UTC, tdejoigny-ledger commented on .github/workflows/ci-workflow.yml
> +      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-legacy:latest
why legacy instead of lite ?

2023-03-02 18:07 UTC, tdejoigny-ledger commented on .github/workflows/ci-workflow.yml
We need to add the `guidelines_enforcer.yml` reusable workflow

2023-03-13 09:03 UTC, agrojean-ledger commented on .github/workflows/ci-workflow.yml
> +      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-legacy:latest
@tdejoigny-ledger because the new builder is based on `alpine` Linux and the unit test job can't run on it as it is. So I use the legacy (`ubuntu` based) that works.

2023-03-13 09:06 UTC, agrojean-ledger commented on tests/requirements.txt
> +# pytest>=6.1.1,<7.0.0
Done.

2023-03-13 09:35 UTC, agrojean-ledger commented on .github/workflows/ci-workflow.yml
@tdejoigny-ledger I added the job but I will comment it as it does not work when code for stax is not implemented. We will enable it later.

2023-03-13 09:44 UTC, tdejoigny-ledger approved these changes

2023-03-13 13:20 UTC, merged